# HubsArena
lobby-coordinates:
  world: w_kitpvp
  x: -110.5
  y: 28
  z: 175.5
  yaw: 0
  pitch: 0

# possible placeholders: %player%, %hero%, %alt_hero%
on-arena-join-notifications:
  - 'На Арену зашёл %hero% %player%'
  - '%player% в образе %alt_hero% сейчас будет нагибать!'

menu:
  material: 'COMPASS'
  name: '&e&lКит меню'
  lore:
    - "&fКликни, чтобы"
    - "&6&l1πДВЕРЬАСИТЬСЯ"
  chesterton-file: "arena-menu"
  chesterton-items:
    18: "KNIGHT"
    27: "ARCHER"

arena-spawns:
  - '-13.5:64:-150.5'
  - '-54.5:64:-175.5'


# Testing data

sounds:
  FIRST_TEST_SOUND:
    sound: "BLOCK_STONE_PRESSURE_PLATE_CLICK_ON"
    offsetX: 0
    offsetY: 0
    offsetZ: 0
    volume: 1.0
    pitch: 1.0

  SECOND_TEST_SOUND:
    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    offsetX: 0
    offsetY: 0
    offsetZ: 0
    volume: 1.0
    pitch: 1.0

effects:
  FIRST_TEST_EFFECT:
    effectType: "SPEED"
    duration: 9999999
    amplifier: 0

  SECOND_TEST_EFFECT:
    effectType: "INCREASE_DAMAGE"
    duration: 40
    amplifier: 3

items:
  FIRST_TEST_ITEM:
    material: "BEETROOT_SOUP"
    name: "&lЦелебный супчик"
    lore:
      - "&6Вкусно, пиздец!)))"

  SECOND_TEST_ITEM:
    material: "LEATHER_HELMET"
    name: "&lШляпа лучника"
    color: 6192150
    enchantments:
      - "PROTECTION_ENVIRONMENTAL"
    levels:
      - 2

miitems:
  FIRST_TEST_MI_ITEM:
    itemType: "sword"
    itemName: "KITPVP_PYROSWORD"

  SECOND_TEST_MI_ITEM:
    itemType: "sword"
    itemName: "KITPVP_PYROSWORD"

actions:
  FIRST_TEST_ACTION:
    clickType: "RIGHT"
    item: "FIRST_TEST_ITEM"
    cooldownInTicks: 20
    manaCost: 3

  SECOND_TEST_ACTION:
    clickType: "SHIFT_LEFT"
    item: "SECOND_TEST_ITEM"
    cooldownInTicks: 80
    manaCost: 0

particles:
  TEST_NORMAL_PARTICLE:
    particle: "DRAGON_BREATH"
    offsetX: 0
    offsetY: 2
    offsetZ: 0
    spreadX: 1
    spreadY: 1
    spreadZ: 1
    count: 10
    force: true
    repeatTicks: 0

  TEST_DIRECTIONAL_PARTICLE:
    particle: "SMOKE_LARGE"
    offsetX1: 0
    offsetY1: 0
    offsetZ1: 0
    offsetX2: 0
    offsetY2: 4
    offsetZ2: 0
    speed: 1
    count: 10
    force: false
    repeatTicks: 0

  TEST_REDSTONE_PARTICLE:
    offsetX: 0
    offsetY: 0
    offsetZ: 0
    spreadX: 1
    spreadY: 1
    spreadZ: 1
    red: 0
    green: 255
    blue: 0
    size: 3
    count: 10
    force: false
    repeatTicks: 0

  TEST_SPELL_MOB_PARTICLE:
    particle: "SPELL_MOB"
    offsetX: 0
    offsetY: 0
    offsetZ: 0
    red: 0
    green: 0
    blue: 255
    randomColorCoefficient: 1
    count: 10
    force: false
    repeatTicks: 0

  TEST_NOTE_PARTICLE:
    offsetX: 0
    offsetY: 0
    offsetZ: 0
    colorID: 5
    count: 10
    force: false
    repeatTicks: 0

  TEST_ITEM_PARTICLE:
    particle: "ITEM_CRACK"
    offsetX: 0
    offsetY: 0
    offsetZ: 0
    spreadX: 1
    spreadY: 1
    spreadZ: 1
    material: "BEEF"
    count: 10
    force: false
    repeatTicks: 0

  TEST_BLOCK_PARTICLE:
    particle: "FALLING_DUST"
    offsetX: 0
    offsetY: 0
    offsetZ: 0
    spreadX: 1
    spreadY: 1
    spreadZ: 1
    material: "SAND"
    count: 10
    force: false
    repeatTicks: 0
